apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
  labels:
    name: new-nginx
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: my-web-disk
  containers:
  - name: nginx-pod
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pv-storage
      mountPath: "/var/www/html"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-web-disk
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Mi
        
