apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"events-web"},"name":"events-web","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"events-web","ver":"v1.0"}},"template":{"metadata":{"labels":{"app":"events-web","ver":"v1.0"}},"spec":{"containers":[{"env":[{"name":"SERVER","value":"http://events-api-svc:8082"}],"image":"coursedemos/events-website:v1.0","name":"events-web","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2025-10-23T15:14:00Z"
  generation: 3
  labels:
    app: events-web
  name: events-web
  namespace: default
  resourceVersion: "14385"
  uid: decbf8cd-fc13-441b-835e-447e6c6b3344
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: events-web
      ver: v1.0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: events-web
        ver: v1.0
    spec:
      containers:
      - env:
        - name: SERVER
          value: http://events-api-svc:8082
        image: coursedemos/events-website:v1.0
        imagePullPolicy: IfNotPresent
        name: events-web
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-10-23T17:06:57Z"
    lastUpdateTime: "2025-10-23T17:06:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-23T15:14:00Z"
    lastUpdateTime: "2025-10-23T18:28:48Z"
    message: ReplicaSet "events-web-56b966f8cd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
