apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: events-web2
 name: events-web2
spec:
 replicas: 3
 selector:
   matchLabels:
     app: events-web
     ver: v2.0
 template:
   metadata:
     labels:
       app: events-web
       ver: v2.0
   spec:
     containers:
     - image: coursedemos/events-website:v2.0
       name: events-web2
       ports:
       - containerPort: 8080
       env:
       - name: SERVER
         value: "http://events-api-svc:8082"
