apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: userX-cluster        # TODO - modify userX to be your user number
  region: us-east-2
  version: "1.33" 

managedNodeGroups:
  - name: standard-workers
    instanceType: t2.medium
    desiredCapacity: 2

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
